### PR TITLE
fix build of syntax extension

### PR DESCRIPTION
**Pull request by eucpp**

### CODE REVIEW

**Comment by Kakadu** [comment]
@eucpp I think we need to build `plugin` before a `bundle` target. I'm afraid that in your version `pa_minikanren.cmo` will not be installed at all.

**Comment by eucpp** [comment]
@Kakadu I have fixed it, but it seems to work anyway

**Comment by Kakadu** [comment]
rebase+Squash ?

**Comment by dboulytchev** [comment]
So, can I merge it? Any objections?

**Comment by Kakadu** [comment]
yrp

**Pull request merged**
