### PR TITLE
[RFC] Optimize Stream.bind and mplus functions

### PR DESCRIPTION
**Pull request by Kakadu**
Create thunks more rarely which will save some GC time.
But, it changes order of the results, so tests are promoted.

@dboulytchev , I need your opinion.

Many thanks to @eucpp  who spotted it.

### CODE REVIEW

**Comment by dboulytchev** [comment]
This is a bit more strict semantics.. Does this have an essential performance impact? If no, I would prefer to leave is as it was.

**Comment by Kakadu** [comment]
While evaluating 8 thrines original code is 2 times slower (22 seconds vs 11). Allocations seems to cost a lot.

**Comment by dboulytchev** [comment]
Do other tests work? Including those for the paper (in /samples) and those used in your performance evaluation framework?

**Comment by Kakadu** [comment]
`sorto` works, as other tests that I tried.  We spotted it in last Friday, so I'm quite of sure. 

I never tryed tree-insertion test from `samples/` btw.

**Comment by dboulytchev** [comment]
Oh, then try it :)

**Comment by dboulytchev** [comment]
Close for now.

**Pull request closed without merging**
