### PR TITLE
Introduce Stdlib and put nats, bools and lists there

### PR DESCRIPTION
**Pull request by Kakadu**
in collaboration with @eucpp

### CODE REVIEW

**Comment by eucpp** [comment]
I approve that. It's convenient to have relational data-structures in separate module.

**Comment by dboulytchev** [comment]
I don't mind splitting the library in two modules (to ease the development/support), but I don't find it convenient to use --- now everyone has to remember, which feature resides where. Can we work it around by, say, including the stdlib into the main module, preserving the sources in different files?

**Comment by Kakadu** [comment]
I see two approaches to fix this but I can't decide which one I dislike less.

1) we can rename `MiniKanren.ml` into `MiniKanrenImpl.ml` and include two modules in a new `MiniKanren.ml`. I'm afraid all three modules will be visible from the outside

2) We can rewrite MiniKanrenStd as a functor that takes basic implementation of MiniKanren and include application of this functor in the end of `MiniKanren.ml`. It seems that we will need to include all FmapN to the functor's argument signature and it will be very big.

Any ideas?

**Comment by eucpp** [comment]
@Kakadu 

I think that first option isn't so bad. In fact, MiniKanren.ml will be just a convenient way to include ALL library. And still user will have an opportunity to include only needed stuff (say, just MiniKanrenImpl without std library).

I would only rename MiniKanrenImp to MiniKanrenCore or smthng like that.

**Comment by Kakadu** [comment]
I followed 1st approach. @eucpp can you check that your code compiles with a new version?

**Comment by eucpp** [comment]
@Kakadu yes, it's OK

**Pull request merged**
